CREATE TABLE TB_DD_NHN(
    NHN_UID INT NOT NULL AUTO_INCREMENT,
    NHN_DATE DATE ,
    NHN_END_PRICE VARCHAR(1000) DEFAULT '0' ,
    NHN_UP_DOWN_PRICE VARCHAR(1000) DEFAULT '0',
    NHN_START_PRICE VARCHAR(1000) DEFAULT '0' ,
    NHN_MAX_PRICE VARCHAR(1000) DEFAULT '0' ,
    NHN_MIN_PRICE VARCHAR(1000) DEFAULT '0' ,
    NHN_TRANSACTION VARCHAR(1000) DEFAULT '0' ,

    PRIMARY KEY (NHN_UID , NHN_DATE)
);
